title: "Michał Siejak :: programming portfolio &amp; personal website"
pagetitle: "Michał Siejak :: Developer Portfolio"
description: "Personal website &amp; programming portfolio of Michał Siejak."
keywords: portfolio cv programming demoscene computer graphics
homepage: Portfolio
